# Generated by Django 4.2.2 on 2023-06-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="title",
        ),
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
